### ISSUE TITLE
carousel column width

### ISSUE THREAD

**Issue by jesspherron** [mstaragrieb/Webring#1]
column widths for the carousel shouldn't go below 200 px wide 
![Screen Shot 2020-06-25 at 6 46 06 PM](https://user-images.githubusercontent.com/6867452/85812206-e2c4d200-b714-11ea-868d-aa8fa7a452ae.png)

**Comment by mstaragrieb** [comment]
Curious what browser/size on all of these, just to replicate.

**Comment by mstaragrieb** [comment]
Fixed, no frame goes <200px or >300px;
