### ISSUE TITLE
"[>] next" animation speed

### ISSUE THREAD

**Issue by jesspherron** [mstaragrieb/Webring#12]
When you click the [>] arrows to go back and forth along the carousel, can we have the animation have an ease-out? so it starts moving fast, then slows to a stop? 
Also, it looks like the animation takes a full second. Can we shorten it to .75 of a second, with the ease-out? 

would it be possible to put the ease-out on the animation when you mouse-drag the whole carousel too? It'll help smooth it out, even if it takes as long and acts the same.

**Comment by mstaragrieb** [comment]
It was at .6, or 600 ms, I set it to 400 and changed the easing to ease-out from linear. FWIW https://glidejs.com/docs/ has a lot of things that we can use to dial the effects off the shelf.
