### ISSUE TITLE
layout of comic library gets large gap in the middle

### ISSUE THREAD

**Issue by jesspherron** [mstaragrieb/Webring#2]
between the 2nd and 3rd columns there appears a gap when the browser is widened
![Screen Shot 2020-06-25 at 6 52 59 PM](https://user-images.githubusercontent.com/6867452/85812306-1b64ab80-b715-11ea-8b68-b2916da2f4db.png)

**Comment by mstaragrieb** [comment]
Fixed in Commit "Fixed Issue with Gap"
