### ISSUE TITLE
link color not changing back after click

### ISSUE THREAD

**Issue by jesspherron** [mstaragrieb/Webring#3]
After clicking on a link, it stays Primary Variant; it should turn back into Primary
![Screen Shot 2020-06-25 at 6 54 04 PM](https://user-images.githubusercontent.com/6867452/85812403-5961cf80-b715-11ea-8369-deab8f18510c.png)

**Comment by mstaragrieb** [comment]
Can you confirm if this is still happening?

**Comment by mstaragrieb** [comment]
I think this will be a non-issue when there is a page there as it will load to a new one, so I would like to close for now and re-open if it an issue later.

**Comment by mstaragrieb** [comment]
Closing.
