### ISSUE TITLE
The comic library's filter has only one filter working at a time

### ISSUE THREAD

**Issue by jesspherron** [mstaragrieb/Webring#4]
The filter in the comic library section should be additive (? I think that's the right term here!) so:
1. it shows all of the comics
2. if the user presses GENRE A, then everything withOUT that genre disappears
3. if the user presses GENRE B, then everything WITHOUT GENRE A OR GENRE B would disappear

So the user would ONLY be seeing comics that have BOTH A & B

if this is too complicated for a version 1, that's fine, we can keep it at one genre at a time.

![Screen Shot 2020-06-25 at 6 55 15 PM](https://user-images.githubusercontent.com/6867452/85812556-d2612700-b715-11ea-8bd8-5a0c5f3cc4ba.png)

**Comment by mstaragrieb** [comment]
Should be good now
