### ISSUE TITLE
Behavior of Hover action in GIF form

### ISSUE THREAD

**Issue by jesspherron** [mstaragrieb/Webring#8]
![HOVER ANIM 1](https://user-images.githubusercontent.com/6867452/85817094-e01ca980-b721-11ea-8045-fbdc9a562253.gif)

See the invision for the Hover states in both the carousel and the comic library! 

If we can get this nice easing motion, that would be *chef's kiss*

**Comment by mstaragrieb** [comment]
Complete, Added a text color change which looked nice but can remove. Please Validate
